### ISSUE TITLE
App logo design

### ISSUE THREAD

**Issue by hawariMuflihMunte** [hawariMuflihMunte/E-Commerce#5]
Pembuatan desain kasar dari logo dari aplikasi yang akan dirancang dan dibangun

**Comment by iqbaalma** [comment]
![Image](https://user-images.githubusercontent.com/104726883/222877006-45057adb-a1fc-489e-b6b0-9f1463252679.jpg)

**Comment by hawariMuflihMunte** [comment]
Awokawokawok

**Comment by iqbaalma** [comment]
![Image](https://user-images.githubusercontent.com/104726883/222878666-d87fd34c-5666-4b7b-b255-5df3e42787b7.png)
![Image](https://user-images.githubusercontent.com/104726883/222878665-6b886957-e669-49a1-927e-d8f595c0efe7.png)

**Comment by hawariMuflihMunte** [comment]
Keren awokawok

**Comment by hawariMuflihMunte** [comment]
Kita close dlu nih `issue` nya ?
